jenkins:
  securityRealm:
    local:
      users:
        - id: "gh_user"
          password: "p@ssw0rd"



# Tool Configuration
tool:
  git:
    installations:
      - name: "Default"
        home: "/usr/bin/git"
  maven:
    installations:
      - name: maven3
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.8.4"

# Sample Job Configuration
jobs:
  - script: >
      pipelineJob('example-pipeline-job') {
      definition {
        cps {
          script("""
            pipeline {
                agent any
                stages {
                    stage('Hello') {
                        steps {
                            echo 'Hello, Jenkins!'
                            sh 'date'
                        }
                    }
                }
            }
          """.stripIndent())
          sandbox(true)
        }
      }
    }

